# Simone - A theme for Bolt.

sidebar: false

# https://unsplash.imgix.net/18/stones.JPG?q=75&fm=jpg&auto=format&s=76ebb60f03b158f746c34a088ab6ea37
header_image: images/stones.jpg
header_textcolor: "#FFF"

